# Generated by Django 5.2.9 on 2026-02-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('block', models.CharField(choices=[('rano', 'Rano'), ('przedpołudniem', 'Przedpołudniem'), ('popołudniu', 'Popołudniu'), ('wieczorem', 'Wieczorem')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('color', models.CharField(choices=[('zielony', 'Zielony'), ('czerwony', 'Czerwony'), ('niebieski', 'Niebieski'), ('blekitny', 'Błękitny'), ('fioletowy', 'Fioletowy'), ('rozowy', 'Różowy'), ('pomaranczowy', 'Pomarańczowy'), ('zolty', 'Żółty'), ('szary', 'Szary')], max_length=50)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cadre')),
            ],
        ),
    ]
