# Generated by Django 5.2.9 on 2026-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
