# Generated by Django 5.2.9 on 2026-02-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_activity_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=models.CharField(choices=[('#2e8746', 'Zielony'), ('#940f0a', 'Czerwony'), ('#263999', 'Niebieski'), ('#3a79b0', 'Błękitny'), ('#663294', 'Fioletowy'), ('#c73aaf', 'Różowy'), ('#c7793a', 'Pomarańczowy'), ('#a2a825', 'Żółty'), ('#63635b', 'Szary')], max_length=50),
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='outlines/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cadre')),
            ],
        ),
    ]
