# Generated by Django 5.2.9 on 2026-02-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='team',
        ),
        migrations.AddField(
            model_name='payments',
            name='participant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.participants'),
            preserve_default=False,
        ),
    ]
