# Generated by Django 5.2.9 on 2026-02-09 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_payments_name_remove_payments_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='file',
            field=models.FileField(upload_to='outlines/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'png', 'odt', 'jpeg'])]),
        ),
    ]
