# Generated by Django 5.2.9 on 2026-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_outline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='entire_amount',
            field=models.CharField(default='Niezapłacono'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='installment',
            field=models.CharField(default='Niezapłacono'),
        ),
    ]
