# Generated by Django 5.2.9 on 2026-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_payments_entire_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='entire_amount',
            field=models.CharField(default='Niezapłacono', max_length=20),
        ),
        migrations.AlterField(
            model_name='payments',
            name='installment',
            field=models.CharField(default='Niezapłacono', max_length=20),
        ),
    ]
